/**
 * Text Export
 * Generate plain text file from recognized text
 */

import { ExportOptions } from './ExportService';

export async function generateText(text: string, options: ExportOptions): Promise<Blob> {
  const content = createTextContent(text, options);
  return new Blob([content], { type: 'text/plain;charset=utf-8' });
}

function createTextContent(text: string, options: ExportOptions): string {
  const lines: string[] = [];
  
  if (options.includeMetadata) {
    const title = options.title || 'SCAN ME Document';
    const date = new Date().toLocaleString();
    
    lines.push('=' .repeat(50));
    lines.push(title);
    lines.push('=' .repeat(50));
    lines.push(`Generated by SCAN ME`);
    lines.push(`Date: ${date}`);
    lines.push('=' .repeat(50));
    lines.push('');
  }
  
  lines.push(text);
  
  if (options.includeMetadata) {
    lines.push('');
    lines.push('-'.repeat(50));
    lines.push('Processed with SCAN ME - Handwriting to Text');
  }
  
  return lines.join('\n');
}
