/**
 * Word Export
 * Generate DOCX from recognized text
 */

import { ExportOptions } from './ExportService';

export async function generateWord(text: string, options: ExportOptions): Promise<Blob> {
  // Note: In production, use docx library
  // import { Document, Packer, Paragraph, TextRun } from 'docx';
  
  const docxContent = createDocxContent(text, options);
  return new Blob([docxContent], { 
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' 
  });
}

function createDocxContent(text: string, options: ExportOptions): string {
  const title = options.title || 'SCAN ME Document';
  const date = new Date().toLocaleDateString();
  
  // Simple DOCX XML structure (placeholder)
  // In production, use docx library for proper DOCX generation
  const document = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Title"/>
      </w:pPr>
      <w:r>
        <w:t>${escapeXml(title)}</w:t>
      </w:r>
    </w:p>
    <w:p>
      <w:r>
        <w:rPr>
          <w:color w:val="666666"/>
          <w:sz w:val="20"/>
        </w:rPr>
        <w:t>Generated by SCAN ME on ${date}</w:t>
      </w:r>
    </w:p>
    <w:p/>
    ${textToParagraphs(text)}
  </w:body>
</w:document>`;

  return document;
}

function textToParagraphs(text: string): string {
  return text.split('\n').map(line => `
    <w:p>
      <w:r>
        <w:t>${escapeXml(line)}</w:t>
      </w:r>
    </w:p>
  `).join('');
}

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
