/**
 * Nigerian Avatar Library
 * Rich collection of realistic human avatars representing diverse Nigerian demographics
 * Includes various professions, ages, ethnicities, and cultural attire
 */

export interface DetailedAvatar {
  id: string;
  name: string;
  gender: 'male' | 'female';
  ageGroup: 'young' | 'middle' | 'senior';
  ethnicity: 'igbo' | 'yoruba' | 'hausa' | 'ijaw' | 'edo' | 'fulani' | 'mixed';
  profession: string;
  description: string;
  skinTone: string;
  skinToneRGB: { r: number; g: number; b: number };
  hairColor: string;
  hairStyle: string;
  eyeColor: string;
  faceShape: 'oval' | 'round' | 'square' | 'heart' | 'oblong';
  outfit: string;
  outfitColors: { primary: string; secondary: string; accent: string };
  accessories: string[];
  culturalAttire?: string;
  voiceType: 'deep' | 'medium' | 'high' | 'soft' | 'strong';
  defaultLanguage: 'english' | 'igbo' | 'yoruba' | 'hausa' | 'pidgin';
  personality: string[];
  category: 'medical' | 'traditional' | 'professional' | 'casual' | 'religious' | 'educational';
}

// Comprehensive Avatar Library
export const NIGERIAN_AVATAR_LIBRARY: DetailedAvatar[] = [
  // ==================== MEDICAL PROFESSIONALS ====================
  {
    id: 'dr-adaeze-nwosu',
    name: 'Dr. Adaeze Nwosu',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'igbo',
    profession: 'Senior Consultant Physician',
    description: 'Experienced physician specializing in internal medicine',
    skinTone: '#8B6914',
    skinToneRGB: { r: 139, g: 105, b: 20 },
    hairColor: '#1a1a1a',
    hairStyle: 'professional-bun',
    eyeColor: '#3D2B1F',
    faceShape: 'oval',
    outfit: 'white-coat',
    outfitColors: { primary: '#ffffff', secondary: '#2563eb', accent: '#gold' },
    accessories: ['stethoscope', 'id-badge', 'glasses'],
    voiceType: 'medium',
    defaultLanguage: 'english',
    personality: ['authoritative', 'caring', 'knowledgeable'],
    category: 'medical'
  },
  {
    id: 'dr-emeka-okonkwo',
    name: 'Dr. Emeka Okonkwo',
    gender: 'male',
    ageGroup: 'middle',
    ethnicity: 'igbo',
    profession: 'Surgeon',
    description: 'Skilled general surgeon with 15 years experience',
    skinTone: '#6B4423',
    skinToneRGB: { r: 107, g: 68, b: 35 },
    hairColor: '#1a1a1a',
    hairStyle: 'short-professional',
    eyeColor: '#2C1810',
    faceShape: 'square',
    outfit: 'surgical-scrubs',
    outfitColors: { primary: '#10b981', secondary: '#ffffff', accent: '#059669' },
    accessories: ['surgical-cap', 'mask-around-neck', 'id-badge'],
    voiceType: 'deep',
    defaultLanguage: 'english',
    personality: ['precise', 'calm', 'confident'],
    category: 'medical'
  },
  {
    id: 'nurse-amina-ibrahim',
    name: 'Nurse Amina Ibrahim',
    gender: 'female',
    ageGroup: 'young',
    ethnicity: 'hausa',
    profession: 'Registered Nurse',
    description: 'Compassionate nurse specializing in patient care',
    skinTone: '#C19A6B',
    skinToneRGB: { r: 193, g: 154, b: 107 },
    hairColor: '#1a1a1a',
    hairStyle: 'hijab-covered',
    eyeColor: '#3D2B1F',
    faceShape: 'heart',
    outfit: 'nurse-uniform-hijab',
    outfitColors: { primary: '#3b82f6', secondary: '#ffffff', accent: '#1d4ed8' },
    accessories: ['hijab', 'nurse-watch', 'id-badge'],
    culturalAttire: 'hijab',
    voiceType: 'soft',
    defaultLanguage: 'hausa',
    personality: ['gentle', 'patient', 'attentive'],
    category: 'medical'
  },
  {
    id: 'dr-oluwaseun-adeyemi',
    name: 'Dr. Oluwaseun Adeyemi',
    gender: 'male',
    ageGroup: 'senior',
    ethnicity: 'yoruba',
    profession: 'Chief Medical Director',
    description: 'Distinguished hospital administrator and physician',
    skinTone: '#704214',
    skinToneRGB: { r: 112, g: 66, b: 20 },
    hairColor: '#4a4a4a',
    hairStyle: 'short-grey',
    eyeColor: '#2C1810',
    faceShape: 'oblong',
    outfit: 'formal-suit-coat',
    outfitColors: { primary: '#1e3a5f', secondary: '#ffffff', accent: '#b8860b' },
    accessories: ['glasses', 'stethoscope', 'tie', 'id-badge'],
    voiceType: 'deep',
    defaultLanguage: 'yoruba',
    personality: ['wise', 'authoritative', 'experienced'],
    category: 'medical'
  },
  {
    id: 'nurse-blessing-okafor',
    name: 'Nurse Blessing Okafor',
    gender: 'female',
    ageGroup: 'young',
    ethnicity: 'igbo',
    profession: 'Wound Care Specialist',
    description: 'Expert in wound management and patient education',
    skinTone: '#8B5A2B',
    skinToneRGB: { r: 139, g: 90, b: 43 },
    hairColor: '#1a1a1a',
    hairStyle: 'braids-updo',
    eyeColor: '#3D2B1F',
    faceShape: 'oval',
    outfit: 'nurse-scrubs',
    outfitColors: { primary: '#ec4899', secondary: '#ffffff', accent: '#db2777' },
    accessories: ['nurse-cap', 'gloves', 'id-badge'],
    voiceType: 'medium',
    defaultLanguage: 'igbo',
    personality: ['caring', 'thorough', 'educational'],
    category: 'medical'
  },
  {
    id: 'dr-musa-abdullahi',
    name: 'Dr. Musa Abdullahi',
    gender: 'male',
    ageGroup: 'middle',
    ethnicity: 'hausa',
    profession: 'Anesthesiologist',
    description: 'Specialist in anesthesia and pain management',
    skinTone: '#D2691E',
    skinToneRGB: { r: 210, g: 105, b: 30 },
    hairColor: '#1a1a1a',
    hairStyle: 'short-kufi',
    eyeColor: '#2C1810',
    faceShape: 'round',
    outfit: 'surgical-scrubs-cap',
    outfitColors: { primary: '#0ea5e9', secondary: '#ffffff', accent: '#0284c7' },
    accessories: ['kufi-cap', 'surgical-mask', 'id-badge'],
    culturalAttire: 'kufi',
    voiceType: 'medium',
    defaultLanguage: 'hausa',
    personality: ['calm', 'reassuring', 'precise'],
    category: 'medical'
  },
  {
    id: 'midwife-ngozi-eze',
    name: 'Midwife Ngozi Eze',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'igbo',
    profession: 'Senior Midwife',
    description: 'Experienced midwife with maternal health expertise',
    skinTone: '#9B7653',
    skinToneRGB: { r: 155, g: 118, b: 83 },
    hairColor: '#2b2b2b',
    hairStyle: 'gele-wrapped',
    eyeColor: '#3D2B1F',
    faceShape: 'round',
    outfit: 'nurse-uniform-traditional',
    outfitColors: { primary: '#a855f7', secondary: '#ffffff', accent: '#7c3aed' },
    accessories: ['gele', 'id-badge', 'beads'],
    culturalAttire: 'gele-headwrap',
    voiceType: 'strong',
    defaultLanguage: 'igbo',
    personality: ['nurturing', 'experienced', 'reassuring'],
    category: 'medical'
  },
  {
    id: 'pharmacist-taiwo-johnson',
    name: 'Pharmacist Taiwo Johnson',
    gender: 'male',
    ageGroup: 'young',
    ethnicity: 'yoruba',
    profession: 'Clinical Pharmacist',
    description: 'Medication specialist and patient counselor',
    skinTone: '#8B4513',
    skinToneRGB: { r: 139, g: 69, b: 19 },
    hairColor: '#1a1a1a',
    hairStyle: 'low-fade',
    eyeColor: '#2C1810',
    faceShape: 'oval',
    outfit: 'white-coat-casual',
    outfitColors: { primary: '#ffffff', secondary: '#16a34a', accent: '#15803d' },
    accessories: ['id-badge', 'pen-pocket'],
    voiceType: 'medium',
    defaultLanguage: 'yoruba',
    personality: ['helpful', 'knowledgeable', 'friendly'],
    category: 'medical'
  },
  
  // ==================== TRADITIONAL/CULTURAL ====================
  {
    id: 'chief-obiora-igwe',
    name: 'Chief Obiora Igwe',
    gender: 'male',
    ageGroup: 'senior',
    ethnicity: 'igbo',
    profession: 'Traditional Chief',
    description: 'Respected community leader and elder',
    skinTone: '#704214',
    skinToneRGB: { r: 112, g: 66, b: 20 },
    hairColor: '#808080',
    hairStyle: 'grey-short',
    eyeColor: '#2C1810',
    faceShape: 'square',
    outfit: 'isiagu-chief',
    outfitColors: { primary: '#dc2626', secondary: '#fbbf24', accent: '#1a1a1a' },
    accessories: ['red-cap', 'beads', 'staff', 'eagle-feather'],
    culturalAttire: 'isiagu-with-red-cap',
    voiceType: 'deep',
    defaultLanguage: 'igbo',
    personality: ['wise', 'traditional', 'respected'],
    category: 'traditional'
  },
  {
    id: 'mama-nkechi',
    name: 'Mama Nkechi',
    gender: 'female',
    ageGroup: 'senior',
    ethnicity: 'igbo',
    profession: 'Village Elder / Herbalist',
    description: 'Traditional healer and community grandmother',
    skinTone: '#8B6914',
    skinToneRGB: { r: 139, g: 105, b: 20 },
    hairColor: '#C0C0C0',
    hairStyle: 'grey-wrapped',
    eyeColor: '#3D2B1F',
    faceShape: 'round',
    outfit: 'traditional-wrapper-blouse',
    outfitColors: { primary: '#1e40af', secondary: '#fbbf24', accent: '#ffffff' },
    accessories: ['coral-beads', 'headtie', 'walking-stick'],
    culturalAttire: 'george-wrapper',
    voiceType: 'soft',
    defaultLanguage: 'igbo',
    personality: ['wise', 'nurturing', 'traditional'],
    category: 'traditional'
  },
  {
    id: 'alhaji-suleiman',
    name: 'Alhaji Suleiman Bello',
    gender: 'male',
    ageGroup: 'senior',
    ethnicity: 'hausa',
    profession: 'Community Leader / Imam',
    description: 'Religious leader and community elder',
    skinTone: '#C19A6B',
    skinToneRGB: { r: 193, g: 154, b: 107 },
    hairColor: '#FFFFFF',
    hairStyle: 'white-beard',
    eyeColor: '#2C1810',
    faceShape: 'oblong',
    outfit: 'babban-riga',
    outfitColors: { primary: '#ffffff', secondary: '#1e40af', accent: '#fbbf24' },
    accessories: ['turban', 'tasbih', 'glasses'],
    culturalAttire: 'babban-riga-turban',
    voiceType: 'deep',
    defaultLanguage: 'hausa',
    personality: ['pious', 'wise', 'respected'],
    category: 'traditional'
  },
  {
    id: 'hajiya-fatima',
    name: 'Hajiya Fatima Yusuf',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'hausa',
    profession: 'Community Health Educator',
    description: 'Respected woman leader promoting health education',
    skinTone: '#D2B48C',
    skinToneRGB: { r: 210, g: 180, b: 140 },
    hairColor: '#1a1a1a',
    hairStyle: 'hijab-elegant',
    eyeColor: '#3D2B1F',
    faceShape: 'oval',
    outfit: 'abaya-elegant',
    outfitColors: { primary: '#7c3aed', secondary: '#fbbf24', accent: '#ffffff' },
    accessories: ['hijab', 'gold-jewelry', 'henna'],
    culturalAttire: 'abaya-with-hijab',
    voiceType: 'medium',
    defaultLanguage: 'hausa',
    personality: ['respected', 'educated', 'influential'],
    category: 'traditional'
  },
  {
    id: 'chief-oladele-adesanya',
    name: 'Chief Oladele Adesanya',
    gender: 'male',
    ageGroup: 'senior',
    ethnicity: 'yoruba',
    profession: 'Yoruba Chief / Oba Representative',
    description: 'Traditional Yoruba leader and cultural ambassador',
    skinTone: '#704214',
    skinToneRGB: { r: 112, g: 66, b: 20 },
    hairColor: '#808080',
    hairStyle: 'grey-distinguished',
    eyeColor: '#2C1810',
    faceShape: 'square',
    outfit: 'agbada-royal',
    outfitColors: { primary: '#fbbf24', secondary: '#ffffff', accent: '#dc2626' },
    accessories: ['fila-cap', 'beads', 'horsetail-whisk', 'staff'],
    culturalAttire: 'agbada-with-fila',
    voiceType: 'deep',
    defaultLanguage: 'yoruba',
    personality: ['regal', 'wise', 'commanding'],
    category: 'traditional'
  },
  {
    id: 'iyalode-adunni',
    name: 'Iyalode Adunni Ogundimu',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'yoruba',
    profession: "Women's Leader",
    description: 'Traditional title holder representing women',
    skinTone: '#8B5A2B',
    skinToneRGB: { r: 139, g: 90, b: 43 },
    hairColor: '#1a1a1a',
    hairStyle: 'gele-elaborate',
    eyeColor: '#3D2B1F',
    faceShape: 'heart',
    outfit: 'aso-oke-iro-buba',
    outfitColors: { primary: '#ec4899', secondary: '#fbbf24', accent: '#ffffff' },
    accessories: ['gele', 'coral-beads', 'gold-jewelry', 'ipele'],
    culturalAttire: 'aso-oke-complete',
    voiceType: 'strong',
    defaultLanguage: 'yoruba',
    personality: ['dignified', 'eloquent', 'influential'],
    category: 'traditional'
  },
  
  // ==================== PROFESSIONAL/BUSINESS ====================
  {
    id: 'banker-chidi-okoro',
    name: 'Chidi Okoro',
    gender: 'male',
    ageGroup: 'young',
    ethnicity: 'igbo',
    profession: 'Bank Manager',
    description: 'Young professional in the banking sector',
    skinTone: '#8B4513',
    skinToneRGB: { r: 139, g: 69, b: 19 },
    hairColor: '#1a1a1a',
    hairStyle: 'clean-cut',
    eyeColor: '#2C1810',
    faceShape: 'oval',
    outfit: 'business-suit',
    outfitColors: { primary: '#1e3a5f', secondary: '#ffffff', accent: '#dc2626' },
    accessories: ['tie', 'watch', 'cufflinks'],
    voiceType: 'medium',
    defaultLanguage: 'english',
    personality: ['professional', 'articulate', 'confident'],
    category: 'professional'
  },
  {
    id: 'lawyer-yetunde-williams',
    name: 'Barrister Yetunde Williams',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'yoruba',
    profession: 'Senior Advocate',
    description: 'Distinguished lawyer and legal expert',
    skinTone: '#6B4423',
    skinToneRGB: { r: 107, g: 68, b: 35 },
    hairColor: '#1a1a1a',
    hairStyle: 'professional-straight',
    eyeColor: '#3D2B1F',
    faceShape: 'oval',
    outfit: 'legal-attire',
    outfitColors: { primary: '#1a1a1a', secondary: '#ffffff', accent: '#1a1a1a' },
    accessories: ['wig', 'gown', 'bands', 'briefcase'],
    voiceType: 'strong',
    defaultLanguage: 'english',
    personality: ['eloquent', 'sharp', 'authoritative'],
    category: 'professional'
  },
  {
    id: 'engineer-usman-garba',
    name: 'Engr. Usman Garba',
    gender: 'male',
    ageGroup: 'middle',
    ethnicity: 'hausa',
    profession: 'Civil Engineer',
    description: 'Construction and infrastructure expert',
    skinTone: '#C19A6B',
    skinToneRGB: { r: 193, g: 154, b: 107 },
    hairColor: '#1a1a1a',
    hairStyle: 'short-neat',
    eyeColor: '#2C1810',
    faceShape: 'square',
    outfit: 'smart-casual-hardhat',
    outfitColors: { primary: '#f59e0b', secondary: '#1e3a5f', accent: '#ffffff' },
    accessories: ['hardhat', 'safety-vest', 'blueprints'],
    voiceType: 'medium',
    defaultLanguage: 'hausa',
    personality: ['practical', 'methodical', 'reliable'],
    category: 'professional'
  },
  {
    id: 'entrepreneur-ada-obi',
    name: 'Ada Obi',
    gender: 'female',
    ageGroup: 'young',
    ethnicity: 'igbo',
    profession: 'Tech Entrepreneur',
    description: 'Young startup founder and innovator',
    skinTone: '#9B7653',
    skinToneRGB: { r: 155, g: 118, b: 83 },
    hairColor: '#1a1a1a',
    hairStyle: 'natural-afro',
    eyeColor: '#3D2B1F',
    faceShape: 'heart',
    outfit: 'smart-casual-modern',
    outfitColors: { primary: '#7c3aed', secondary: '#ffffff', accent: '#a855f7' },
    accessories: ['laptop', 'smartwatch', 'earbuds'],
    voiceType: 'high',
    defaultLanguage: 'english',
    personality: ['innovative', 'energetic', 'inspiring'],
    category: 'professional'
  },
  
  // ==================== EDUCATIONAL ====================
  {
    id: 'professor-okonjo',
    name: 'Prof. Ifeoma Okonjo',
    gender: 'female',
    ageGroup: 'senior',
    ethnicity: 'igbo',
    profession: 'University Professor',
    description: 'Distinguished academic and researcher',
    skinTone: '#8B6914',
    skinToneRGB: { r: 139, g: 105, b: 20 },
    hairColor: '#4a4a4a',
    hairStyle: 'grey-natural',
    eyeColor: '#3D2B1F',
    faceShape: 'oval',
    outfit: 'academic-formal',
    outfitColors: { primary: '#1e3a5f', secondary: '#ffffff', accent: '#dc2626' },
    accessories: ['glasses', 'books', 'university-pin'],
    voiceType: 'medium',
    defaultLanguage: 'english',
    personality: ['intellectual', 'patient', 'inspiring'],
    category: 'educational'
  },
  {
    id: 'teacher-mr-balogun',
    name: 'Mr. Kayode Balogun',
    gender: 'male',
    ageGroup: 'middle',
    ethnicity: 'yoruba',
    profession: 'Secondary School Teacher',
    description: 'Dedicated teacher passionate about education',
    skinTone: '#704214',
    skinToneRGB: { r: 112, g: 66, b: 20 },
    hairColor: '#1a1a1a',
    hairStyle: 'short-classic',
    eyeColor: '#2C1810',
    faceShape: 'round',
    outfit: 'teacher-formal',
    outfitColors: { primary: '#0ea5e9', secondary: '#ffffff', accent: '#1e3a5f' },
    accessories: ['glasses', 'chalk', 'books'],
    voiceType: 'medium',
    defaultLanguage: 'yoruba',
    personality: ['patient', 'encouraging', 'knowledgeable'],
    category: 'educational'
  },
  {
    id: 'headmistress-halima',
    name: 'Mrs. Halima Abubakar',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'hausa',
    profession: 'School Headmistress',
    description: 'School administrator and education leader',
    skinTone: '#D2B48C',
    skinToneRGB: { r: 210, g: 180, b: 140 },
    hairColor: '#1a1a1a',
    hairStyle: 'hijab-professional',
    eyeColor: '#3D2B1F',
    faceShape: 'oval',
    outfit: 'professional-hijab',
    outfitColors: { primary: '#16a34a', secondary: '#ffffff', accent: '#15803d' },
    accessories: ['hijab', 'id-badge', 'folder'],
    culturalAttire: 'professional-hijab',
    voiceType: 'strong',
    defaultLanguage: 'hausa',
    personality: ['authoritative', 'caring', 'organized'],
    category: 'educational'
  },
  
  // ==================== CASUAL/EVERYDAY ====================
  {
    id: 'student-chisom',
    name: 'Chisom Nnadi',
    gender: 'female',
    ageGroup: 'young',
    ethnicity: 'igbo',
    profession: 'University Student',
    description: 'Young university student studying medicine',
    skinTone: '#8B5A2B',
    skinToneRGB: { r: 139, g: 90, b: 43 },
    hairColor: '#1a1a1a',
    hairStyle: 'braids-long',
    eyeColor: '#3D2B1F',
    faceShape: 'heart',
    outfit: 'casual-student',
    outfitColors: { primary: '#ec4899', secondary: '#ffffff', accent: '#f59e0b' },
    accessories: ['backpack', 'phone', 'earbuds'],
    voiceType: 'high',
    defaultLanguage: 'pidgin',
    personality: ['cheerful', 'curious', 'relatable'],
    category: 'casual'
  },
  {
    id: 'student-emeka-jr',
    name: 'Emeka Chukwu Jr.',
    gender: 'male',
    ageGroup: 'young',
    ethnicity: 'igbo',
    profession: 'University Student',
    description: 'Young man studying engineering',
    skinTone: '#6B4423',
    skinToneRGB: { r: 107, g: 68, b: 35 },
    hairColor: '#1a1a1a',
    hairStyle: 'low-cut',
    eyeColor: '#2C1810',
    faceShape: 'oval',
    outfit: 'casual-trendy',
    outfitColors: { primary: '#3b82f6', secondary: '#ffffff', accent: '#1a1a1a' },
    accessories: ['snapback', 'phone', 'chain'],
    voiceType: 'medium',
    defaultLanguage: 'pidgin',
    personality: ['cool', 'friendly', 'humorous'],
    category: 'casual'
  },
  {
    id: 'market-woman-mama-nkiru',
    name: 'Mama Nkiru',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'igbo',
    profession: 'Market Trader',
    description: 'Hardworking market woman and entrepreneur',
    skinTone: '#9B7653',
    skinToneRGB: { r: 155, g: 118, b: 83 },
    hairColor: '#1a1a1a',
    hairStyle: 'headtie-market',
    eyeColor: '#3D2B1F',
    faceShape: 'round',
    outfit: 'ankara-wrapper-blouse',
    outfitColors: { primary: '#f59e0b', secondary: '#dc2626', accent: '#16a34a' },
    accessories: ['headtie', 'beads', 'wrapper'],
    culturalAttire: 'ankara-wrapper',
    voiceType: 'strong',
    defaultLanguage: 'igbo',
    personality: ['energetic', 'shrewd', 'maternal'],
    category: 'casual'
  },
  {
    id: 'farmer-mallam-isa',
    name: 'Mallam Isa',
    gender: 'male',
    ageGroup: 'middle',
    ethnicity: 'fulani',
    profession: 'Farmer / Herdsman',
    description: 'Traditional Fulani farmer and cattle rearer',
    skinTone: '#C19A6B',
    skinToneRGB: { r: 193, g: 154, b: 107 },
    hairColor: '#2b2b2b',
    hairStyle: 'short-rural',
    eyeColor: '#2C1810',
    faceShape: 'oblong',
    outfit: 'jalabiya-farmer',
    outfitColors: { primary: '#78716c', secondary: '#d6d3d1', accent: '#44403c' },
    accessories: ['straw-hat', 'staff', 'rope'],
    culturalAttire: 'fulani-jalabiya',
    voiceType: 'deep',
    defaultLanguage: 'hausa',
    personality: ['humble', 'hardworking', 'traditional'],
    category: 'casual'
  },
  {
    id: 'okada-rider-sunday',
    name: 'Sunday Eze',
    gender: 'male',
    ageGroup: 'young',
    ethnicity: 'igbo',
    profession: 'Commercial Motorcyclist',
    description: 'Friendly okada rider and community helper',
    skinTone: '#8B4513',
    skinToneRGB: { r: 139, g: 69, b: 19 },
    hairColor: '#1a1a1a',
    hairStyle: 'short-simple',
    eyeColor: '#2C1810',
    faceShape: 'square',
    outfit: 'casual-rider',
    outfitColors: { primary: '#f59e0b', secondary: '#1a1a1a', accent: '#dc2626' },
    accessories: ['helmet', 'reflective-vest', 'phone'],
    voiceType: 'medium',
    defaultLanguage: 'pidgin',
    personality: ['friendly', 'talkative', 'street-smart'],
    category: 'casual'
  },
  
  // ==================== RELIGIOUS ====================
  {
    id: 'pastor-johnson',
    name: 'Pastor Samuel Johnson',
    gender: 'male',
    ageGroup: 'middle',
    ethnicity: 'yoruba',
    profession: 'Church Pastor',
    description: 'Charismatic church leader and counselor',
    skinTone: '#704214',
    skinToneRGB: { r: 112, g: 66, b: 20 },
    hairColor: '#1a1a1a',
    hairStyle: 'neat-parted',
    eyeColor: '#2C1810',
    faceShape: 'oval',
    outfit: 'pastoral-suit',
    outfitColors: { primary: '#1a1a1a', secondary: '#ffffff', accent: '#7c3aed' },
    accessories: ['bible', 'cross-pin', 'microphone'],
    voiceType: 'deep',
    defaultLanguage: 'english',
    personality: ['charismatic', 'inspiring', 'compassionate'],
    category: 'religious'
  },
  {
    id: 'reverend-sister-grace',
    name: 'Rev. Sister Grace Obiora',
    gender: 'female',
    ageGroup: 'middle',
    ethnicity: 'igbo',
    profession: 'Catholic Nun / Hospital Administrator',
    description: 'Dedicated nun serving in healthcare',
    skinTone: '#8B6914',
    skinToneRGB: { r: 139, g: 105, b: 20 },
    hairColor: '#1a1a1a',
    hairStyle: 'veil-covered',
    eyeColor: '#3D2B1F',
    faceShape: 'heart',
    outfit: 'nun-habit',
    outfitColors: { primary: '#1e3a5f', secondary: '#ffffff', accent: '#1a1a1a' },
    accessories: ['veil', 'cross', 'rosary'],
    culturalAttire: 'nun-habit',
    voiceType: 'soft',
    defaultLanguage: 'english',
    personality: ['serene', 'compassionate', 'devoted'],
    category: 'religious'
  },
  {
    id: 'imam-ahmed',
    name: 'Imam Ahmed Tijjani',
    gender: 'male',
    ageGroup: 'senior',
    ethnicity: 'hausa',
    profession: 'Islamic Scholar / Imam',
    description: 'Learned Islamic teacher and community guide',
    skinTone: '#C19A6B',
    skinToneRGB: { r: 193, g: 154, b: 107 },
    hairColor: '#FFFFFF',
    hairStyle: 'white-beard-long',
    eyeColor: '#2C1810',
    faceShape: 'oblong',
    outfit: 'imam-attire',
    outfitColors: { primary: '#ffffff', secondary: '#16a34a', accent: '#fbbf24' },
    accessories: ['turban', 'tasbih', 'quran', 'glasses'],
    culturalAttire: 'imam-jalabiya-turban',
    voiceType: 'deep',
    defaultLanguage: 'hausa',
    personality: ['scholarly', 'peaceful', 'wise'],
    category: 'religious'
  }
];

// Avatar Categories for filtering
export const AVATAR_CATEGORIES = [
  { id: 'all', name: 'All Avatars', icon: '👥' },
  { id: 'medical', name: 'Medical Professionals', icon: '🏥' },
  { id: 'traditional', name: 'Traditional/Cultural', icon: '👑' },
  { id: 'professional', name: 'Business/Professional', icon: '💼' },
  { id: 'educational', name: 'Educational', icon: '📚' },
  { id: 'casual', name: 'Casual/Everyday', icon: '🚶' },
  { id: 'religious', name: 'Religious', icon: '🙏' }
];

// Ethnicity options
export const ETHNICITIES = [
  { id: 'all', name: 'All Ethnicities' },
  { id: 'igbo', name: 'Igbo' },
  { id: 'yoruba', name: 'Yoruba' },
  { id: 'hausa', name: 'Hausa' },
  { id: 'fulani', name: 'Fulani' },
  { id: 'edo', name: 'Edo' },
  { id: 'ijaw', name: 'Ijaw' }
];

// Helper functions
export const getAvatarsByCategory = (category: string): DetailedAvatar[] => {
  if (category === 'all') return NIGERIAN_AVATAR_LIBRARY;
  return NIGERIAN_AVATAR_LIBRARY.filter(a => a.category === category);
};

export const getAvatarsByEthnicity = (ethnicity: string): DetailedAvatar[] => {
  if (ethnicity === 'all') return NIGERIAN_AVATAR_LIBRARY;
  return NIGERIAN_AVATAR_LIBRARY.filter(a => a.ethnicity === ethnicity);
};

export const getAvatarsByGender = (gender: 'male' | 'female'): DetailedAvatar[] => {
  return NIGERIAN_AVATAR_LIBRARY.filter(a => a.gender === gender);
};

export const searchAvatars = (query: string): DetailedAvatar[] => {
  const lowerQuery = query.toLowerCase();
  return NIGERIAN_AVATAR_LIBRARY.filter(a => 
    a.name.toLowerCase().includes(lowerQuery) ||
    a.profession.toLowerCase().includes(lowerQuery) ||
    a.description.toLowerCase().includes(lowerQuery) ||
    a.ethnicity.toLowerCase().includes(lowerQuery)
  );
};

export default NIGERIAN_AVATAR_LIBRARY;
